on: push
  # release:
    # types: [ created ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
  publish:
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn publish --registry https://registry.npmjs.org
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
